### ISSUE TITLE
the description

### ISSUE THREAD

**Issue by AzeemHadzrie** [KevinPfeiffer/TBS-Online#1]
how the frick did the first section get here??? you not kidding, I wish you in the four!

Anyways, speaking about this one, please change it to become more friendly. Thanks. Plus I also own a old project called IPTV Asia.

**Comment by KevinPfeiffer** [comment]
This is my service! And did you watch at least one channel on TBS Online or are you too lazy to copy the "Raw"-link?

**Comment by AzeemHadzrie** [comment]
look, remove the "how the frick did you get in GitHub?!? no." message. keep the rest.

**Comment by KevinPfeiffer** [comment]
Ohh!! You mean the text!! Sorry about that!

**Comment by KevinPfeiffer** [comment]
It's now removed!
